class ParticleSystem{constructor(slogan='Pushing the Boundaries of AI'){this.canvas=document.getElementById('particles');if(!this.canvas)return;this.ctx=this.canvas.getContext('2d');this.slogan=slogan;this.particles=[];this.textParticles=[];this.mouseX=0;this.mouseY=0;this.isMouseOver=false;this.animationTime=0;this.resize();this.init();this.bindEvents();this.animate();}
resize(){this.canvas.width=window.innerWidth;this.canvas.height=window.innerHeight;}
getFontSize(){const w=window.innerWidth;if(w>=1200)return 68;if(w>=768)return 48;if(w>=480)return 32;return 24;}
sampleTextParticles(){const o=document.createElement('canvas');o.width=this.canvas.width;o.height=this.canvas.height;const c=o.getContext('2d');const s=this.getFontSize();c.font=`700 ${s}px 'Space Grotesk',system-ui`;c.fillStyle='white';c.textAlign='center';c.textBaseline='middle';const padding=40;c.fillText(this.slogan,Math.min(o.width/2,o.width-padding),o.height*0.45);const d=c.getImageData(0,0,o.width,o.height);const p=d.data;const a=[];const step=window.innerWidth<480?6:window.innerWidth<768?5:4;for(let i=0;i<p.length;i+=4*step){if(p[i+3]>128){const idx=i/4;const x=(idx%o.width);const y=Math.floor(idx/o.width);a.push({x,y});}}return a;}
init(){this.textParticles=this.sampleTextParticles().map((pt,idx)=>({x:Math.random()*this.canvas.width,y:Math.random()*this.canvas.height,targetX:pt.x,targetY:pt.y,radius:2+Math.random()*0.5,color:['#00C8E8','#5870E8','#9050C8'][Math.floor(Math.random()*3)],delay:Math.random()*300,settled:false,driftPhase:Math.random()*Math.PI*2}));const ac=window.innerWidth<480?20:window.innerWidth<768?40:80;this.particles=Array.from({length:ac},()=>({x:Math.random()*this.canvas.width,y:Math.random()*this.canvas.height,vx:(Math.random()-0.5)*0.3,vy:(Math.random()-0.5)*0.3,radius:1.5+Math.random()*1.5,color:['#00C8E8','#5870E8','#9050C8'][Math.floor(Math.random()*3)],opacity:0.4+Math.random()*0.3}));}
updateText(){this.textParticles.forEach(p=>{const e=Math.max(0,this.animationTime-p.delay);const d=1200;const t=Math.min(1,e/d);if(t<1){const eo=1-Math.pow(1-t,3);p.x+=(p.targetX-p.x)*eo*0.1;p.y+=(p.targetY-p.y)*eo*0.1;}else{p.x=p.targetX;p.y=p.targetY;p.settled=true;const drift=Math.sin(this.animationTime/4500+p.driftPhase)*2;p.x+=drift;p.y+=drift*0.3;}if(this.isMouseOver&&p.settled){const dx=p.x-this.mouseX;const dy=p.y-this.mouseY;const dist=Math.sqrt(dx*dx+dy*dy);if(dist<80){const f=(80-dist)*0.05/(dist||1);p.x+=(dx/(dist||1))*f;p.y+=(dy/(dist||1))*f;}}});}
updateAmbient(){this.particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>this.canvas.width)p.vx*=-1;if(p.y<0||p.y>this.canvas.height)p.vy*=-1;p.x=Math.max(0,Math.min(this.canvas.width,p.x));p.y=Math.max(0,Math.min(this.canvas.height,p.y));});}
draw(){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);this.particles.forEach(p=>{this.ctx.fillStyle=p.color.includes('00C8E8')?'rgba(0,200,232,0.4)':p.color.includes('5870E8')?'rgba(88,112,232,0.3)':'rgba(144,80,200,0.3)';this.ctx.beginPath();this.ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);this.ctx.fill();});this.textParticles.forEach(p=>{this.ctx.fillStyle=p.color.includes('00C8E8')?'rgba(0,200,232,0.88)':p.color.includes('5870E8')?'rgba(88,112,232,0.88)':'rgba(144,80,200,0.88)';this.ctx.beginPath();this.ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);this.ctx.fill();});}
animate(){if(!document.hidden&&this.ctx){this.animationTime+=16;this.updateText();this.updateAmbient();this.draw();}requestAnimationFrame(()=>this.animate());}
bindEvents(){this.canvas.addEventListener('mouseenter',()=>this.isMouseOver=true);this.canvas.addEventListener('mouseleave',()=>this.isMouseOver=false);this.canvas.addEventListener('mousemove',e=>{this.mouseX=e.clientX;this.mouseY=e.clientY;});window.addEventListener('resize',()=>{this.resize();this.init();});}
}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;new ParticleSystem();});}else{if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){new ParticleSystem();}}
